env:
  APP_REFRESH: true

http:
  address: 0.0.0.0:8080
  workers:
    command: 'php vendor/spiral/roadrunner-laravel/bin/rr-worker' # for windows: `php vendor/spiral/roadrunner-laravel/bin/rr-worker`
    # command: 'php ./vendor/bin/rr-worker' # for windows: `php vendor/spiral/roadrunner-laravel/bin/rr-worker`
    pool:
      numWorkers: 4
      maxJobs: 64 # jobs limitation is important

static:
  dir: 'public'
